// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {terminal} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateWorkspace(arg1:string,arg2:string):Promise<workspace.Workspace>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function GetAvailableShells():Promise<Array<terminal.ShellInfo>>;

export function GetConfig():Promise<terminal.Config>;

export function GetOrCreateTerminal(arg1:string,arg2:string):Promise<string>;

export function GetTerminalBuffer(arg1:string):Promise<string>;

export function ListWorkspaces():Promise<Array<workspace.Workspace>>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveConfig(arg1:terminal.Config):Promise<void>;

export function SaveWorkspace(arg1:workspace.Workspace):Promise<void>;

export function SelectDirectory():Promise<string>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
