// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateTerminal(arg1:string):Promise<string>;

export function CreateWorkspace(arg1:string,arg2:string):Promise<main.Workspace>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function ListWorkspaces():Promise<Array<main.Workspace>>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveWorkspace(arg1:main.Workspace):Promise<void>;

export function SelectDirectory():Promise<string>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
