// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateWorkspace(arg1:string,arg2:string):Promise<models.Workspace>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function GetAvailableShells():Promise<Array<models.ShellInfo>>;

export function GetConfig():Promise<models.Config>;

export function GetOpenPorts():Promise<Array<models.PortInfo>>;

export function GetOrCreateTerminal(arg1:string,arg2:string):Promise<string>;

export function GetSystemStats():Promise<models.SystemStats>;

export function GetTerminalBuffer(arg1:string):Promise<string>;

export function ListWorkspaces():Promise<Array<models.Workspace>>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveConfig(arg1:models.Config):Promise<void>;

export function SaveWorkspace(arg1:models.Workspace):Promise<void>;

export function SelectDirectory():Promise<string>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
